apiVersion: v1
kind: Service
metadata:
  name: innovatech-backend-despachos
  namespace: innovatech
spec:
  selector:
    app: innovatech-backend-despachos
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
