apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-backend-ventas
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: innovatech-backend-ventas
  template:
    metadata:
      labels:
        app: innovatech-backend-ventas
    spec:
      containers:
        - name: innovatech-backend-ventas
          image: 291271868902.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend:ventas-v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: innovatech-db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: ventas_db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1Gi"