apiVersion: v1
kind: Service
metadata:
  name: innovatech-backend-ventas
  namespace: innovatech
spec:
  selector:
    app: innovatech-backend-ventas
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP