apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-db
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovatech-db
  template:
    metadata:
      labels:
        app: innovatech-db
    spec:
      containers:
        - name: innovatech-db
          image: 291271868902.dkr.ecr.us-east-1.amazonaws.com/innovatech-db:eks-v1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"